export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Profile} from './Profile'
export {default as NotFound} from './NotFound'
export {default as Category} from './Category'
export {default as Upload} from './Upload'